#!/usr/bin/env bash
# bootstrap/50-snapraid.sh — parity protection over the mergerfs pool.
#
# SnapRAID is not RAID. Parity is computed on a schedule, not continuously, so
# anything written since the last sync is unprotected — and a file deleted
# before a sync is, after that sync, gone for good. That trade is what buys
# per-drive independence: every drive holds an ordinary ext4 filesystem you can
# read in any machine, and losing two drives loses only what was on those two.
#
# Nothing here writes to a pool drive's *contents*. It writes parity and
# content files, which is the job.
#
# Idempotent.

# shellcheck source=lib/common.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"

require_root
require_installed_system
require_cmd findmnt awk
load_host_conf
load_drives_conf

SNAPRAID_CONF=/etc/snapraid.conf
CONTENT_DIR=/var/lib/snapraid

mountpoint_for() { printf '/mnt/%s\n' "${1,,}"; }

# ---------------------------------------------------------------------------
# The pool has to be there first
# ---------------------------------------------------------------------------
report_drives || die "refusing to configure SnapRAID against a pool that does not match $DRIVES_CONF"

for s in "${DRIVE_SERIALS[@]}"; do
    [[ "${DRIVE_ROLE[$s]}" == "ssd" ]] && continue
    m="$(mountpoint_for "${DRIVE_LABEL[$s]}")"
    findmnt -M "$m" >/dev/null 2>&1 \
        || die "$m is not mounted — run bootstrap/40-storage.sh first"
done

aur_install snapraid

# ---------------------------------------------------------------------------
# snapraid.conf
# ---------------------------------------------------------------------------
# Generated from drives.conf for the same reason fstab's block is: a second
# copy of the drive table is the drift the table exists to prevent.
#
# Content files are the array's index. SnapRAID needs a majority of them
# readable to work, so they go on every data drive AND on the SSD — the SSD
# copy is the one that survives losing a drive, and the pool copies are the
# ones that survive losing the SSD.
run mkdir -p -- "$CONTENT_DIR"

parity_serial="$(serials_with_role parity)"
parity_mnt="$(mountpoint_for "${DRIVE_LABEL[$parity_serial]}")"

conf_tmp="$(mktemp)"
{
    printf '# Generated by bootstrap/50-snapraid.sh from drives.conf. Do not edit here.\n'
    printf '\n'
    printf 'parity %s/snapraid.parity\n' "$parity_mnt"
    printf '\n'
    printf 'content %s/snapraid.content\n' "$CONTENT_DIR"
    n=0
    for s in "${DRIVE_SERIALS[@]}"; do
        [[ "${DRIVE_ROLE[$s]}" == "data" ]] || continue
        printf 'content %s/snapraid.content\n' "$(mountpoint_for "${DRIVE_LABEL[$s]}")"
    done
    printf '\n'
    for s in "${DRIVE_SERIALS[@]}"; do
        [[ "${DRIVE_ROLE[$s]}" == "data" ]] || continue
        n=$(( n + 1 ))
        printf 'data d%d %s/\n' "$n" "$(mountpoint_for "${DRIVE_LABEL[$s]}")"
    done
    cat <<'EOF'

# Never protect these.
exclude *.unrecoverable
exclude /tmp/
exclude /lost+found/
exclude .Trash-*/
exclude /.snapshots/
exclude *.!sync

# Camera footage is deliberately NOT excluded, which is a reversal of the
# original plan. It is churning, replaceable data and parity for it is arguably
# waste — but there are no cameras yet, and excluding a directory that does not
# exist is a decision made blind. Revisit when cameras are actually bought.
# exclude /cameras/

# 256 KiB blocks: the default, and right for an array of this size. Larger
# blocks shrink the content files but waste parity on small files.
blocksize 256

# Checkpoint a long sync every 250 GB, so an interrupted run does not start over.
autosave 250
EOF
} > "$conf_tmp"

if [[ -f "$SNAPRAID_CONF" ]] && cmp -s -- "$conf_tmp" "$SNAPRAID_CONF"; then
    rm -f -- "$conf_tmp"
else
    log "writing $SNAPRAID_CONF"
    run install -Dm644 -- "$conf_tmp" "$SNAPRAID_CONF"
    rm -f -- "$conf_tmp"
fi

# ---------------------------------------------------------------------------
# The sync wrapper and its timers
# ---------------------------------------------------------------------------
# See the comment block in the wrapper for why `snapraid sync` is never run
# directly from a timer. Short version: an unmounted data drive reads as
# "every file deleted", and syncing that is unrecoverable.
install_file usr/local/bin/snapraid-sync 0755
install_file etc/systemd/system/snapraid-sync.service
install_file etc/systemd/system/snapraid-sync.timer
install_file etc/systemd/system/snapraid-scrub.service
install_file etc/systemd/system/snapraid-scrub.timer
unit_reload

unit_enable snapraid-sync.timer
unit_enable snapraid-scrub.timer
run systemctl start snapraid-sync.timer snapraid-scrub.timer

# ---------------------------------------------------------------------------
# First sync
# ---------------------------------------------------------------------------
# Run it now rather than waiting for 03:00, so the array is protected today and
# any configuration mistake surfaces while you are sitting here. On an empty
# pool this takes seconds.
if [[ ! -e "${parity_mnt}/snapraid.parity" ]]; then
    log "first sync (fast — the pool is empty)"
    run /usr/local/bin/snapraid-sync
fi

log "snapraid status"
snapraid --conf "$SNAPRAID_CONF" status >&2 || warn "snapraid status reported a problem"

systemctl list-timers --no-pager 'snapraid-*' >&2 || true

ok "SnapRAID configured — parity on $parity_mnt"
