#!/usr/bin/env bash
# bootstrap/60-alerting.sh — make the machine tell you when something is wrong.
#
# Three mechanisms, because they fail in different ways:
#
#   ntfy         the host noticing its own problem and pushing a message.
#                Useless when the host is dead.
#   Healthchecks a hosted dead-man switch. Alerts on SILENCE, which is the only
#                way a dead host gets reported at all.
#   smartd       continuous attribute watching, with persistent state files so
#                a change across a reboot is still seen as a change.
#
# Idempotent.

# shellcheck source=lib/common.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"

require_root
require_installed_system
load_host_conf
load_drives_conf

# This is the script that actually uses them, so this is where they become
# mandatory rather than at load time.
require_conf NTFY_SERVER NTFY_TOPIC

ENV_DIR=/etc/homelab
ENV_FILE="$ENV_DIR/alerting.env"

pkg_install smartmontools curl

# ---------------------------------------------------------------------------
# Secrets
# ---------------------------------------------------------------------------
# On public ntfy.sh the topic IS the credential — anyone who knows it reads
# every alert this host sends and can publish convincing fakes to it. Same for
# the Healthchecks URLs: knowing one lets someone keep your dead-man switch
# alive while the machine is down.
#
# 0600, root-owned, and derived from host.conf rather than committed.
run mkdir -p -- "$ENV_DIR"
run chmod 0700 -- "$ENV_DIR"

env_tmp="$(mktemp)"
chmod 0600 -- "$env_tmp"
{
    printf '# Generated by bootstrap/60-alerting.sh from host.conf. Not in git.\n'
    printf 'NTFY_SERVER=%q\n' "$NTFY_SERVER"
    printf 'NTFY_TOPIC=%q\n'  "$NTFY_TOPIC"
    # Every HC_* variable host.conf defines, not a list maintained here.
    # Adding a check to host.conf then reaches the helpers with no edit to this
    # script — and a list in two places is a list that goes stale.
    for v in "${!HC_@}"; do
        printf '%s=%q\n' "$v" "${!v:-}"
    done
} > "$env_tmp"

if [[ -f "$ENV_FILE" ]] && cmp -s -- "$env_tmp" "$ENV_FILE"; then
    dbg "$ENV_FILE already current"
else
    log "writing $ENV_FILE"
    run install -Dm600 -- "$env_tmp" "$ENV_FILE"
fi
rm -f -- "$env_tmp"

# Warn, do not fail. A host with ntfy but no dead-man switch is worse than one
# with both and better than one with neither — but you should know which you have.
for v in "${!HC_@}"; do
    [[ -n "${!v:-}" ]] || warn "$v is empty — that check will never be pinged, and its absence will never be noticed"
done

# ---------------------------------------------------------------------------
# Helpers and units
# ---------------------------------------------------------------------------
install_file usr/local/bin/ntfy-alert       0755
install_file usr/local/bin/hc-ping          0755
install_file usr/local/bin/homelab-heartbeat 0755
install_file usr/local/bin/smartd-ntfy      0755
install_file usr/local/bin/smart-snapshot   0755

install_file etc/systemd/system/ntfy-alert@.service
install_file etc/systemd/system/homelab-heartbeat.service
install_file etc/systemd/system/homelab-heartbeat.timer
install_file etc/systemd/system/smart-snapshot.service
install_file etc/systemd/system/smart-snapshot.timer

# Drop-ins, so 50-snapraid.sh keeps owning those unit files and this script
# keeps owning alerting. Neither needs to know the other's content.
install_file etc/systemd/system/snapraid-sync.service.d/10-alerting.conf
install_file etc/systemd/system/snapraid-scrub.service.d/10-alerting.conf

# ---------------------------------------------------------------------------
# smartd
# ---------------------------------------------------------------------------
# Generated from drives.conf, by-id — smartd.conf conventionally names /dev/sdX,
# which on this machine points at a different drive after a reboot, so every
# alert would name the wrong disk.
smartd_tmp="$(mktemp)"
{
    printf '# Generated by bootstrap/60-alerting.sh from drives.conf.\n'
    printf '#\n'
    printf '# -a          all the standard checks\n'
    printf '# -o on       automatic offline data collection\n'
    printf '# -S on       attribute autosave\n'
    printf '# -n standby,q  do not spin a sleeping drive up just to read it\n'
    printf '# -s ...      short test nightly 02:00, long test Saturday 03:00\n'
    printf '# -W 4,45,55  report a 4 degree jump, warn at 45C, alarm at 55C\n'
    printf '# -m <nomailer> -M exec  no mail; push through ntfy instead\n'
    printf '\n'
    for s in "${DRIVE_SERIALS[@]}"; do
        dev="$(serial_to_dev "$s" 2>/dev/null || true)"
        if [[ -z "$dev" ]]; then
            printf '# %s (%s) not attached at configuration time\n' "$s" "${DRIVE_LABEL[$s]}"
            continue
        fi
        link=''
        for l in "$BYID_DIR/ata-"*"_${s}" "$BYID_DIR/nvme-"*"_${s}"; do
            [[ -e "$l" && "$l" != *-part[0-9]* ]] && { link="$l"; break; }
        done
        [[ -n "$link" ]] || link="$dev"
        printf '# %s — %s\n' "${DRIVE_LABEL[$s]}" "${DRIVE_ROLE[$s]}"
        printf '%s -a -o on -S on -n standby,q -s (S/../.././02|L/../../6/03) -W 4,45,55 -m <nomailer> -M exec /usr/local/bin/smartd-ntfy\n\n' "$link"
    done
} > "$smartd_tmp"

if [[ -f /etc/smartd.conf ]] && cmp -s -- "$smartd_tmp" /etc/smartd.conf; then
    dbg "/etc/smartd.conf already current"
else
    log "writing /etc/smartd.conf"
    run install -Dm644 -- "$smartd_tmp" /etc/smartd.conf
    smartd_changed=1
fi
rm -f -- "$smartd_tmp"

# Persistent state files. Without them smartd re-reads every attribute as a new
# baseline on each restart, so a counter that moved across a reboot — which is
# exactly when drives are stressed — is never reported as having moved.
#
# The drop-in is built from whatever ExecStart the package ships rather than a
# hardcoded command line, so an Arch change to the unit does not silently
# replace it with something wrong.
run mkdir -p /var/lib/smartd
if [[ -z "$DRY_RUN" ]]; then
    base_exec="$(systemctl cat smartd.service 2>/dev/null \
        | awk -F'ExecStart=' '/^ExecStart=/ { print $2; exit }')"
    [[ -n "$base_exec" ]] || die "cannot read smartd.service's ExecStart — refusing to guess it"

    if [[ "$base_exec" == *"--savestates"* || "$base_exec" == *" -s "* ]]; then
        dbg "smartd already saves state"
    else
        dropin=/etc/systemd/system/smartd.service.d/10-savestates.conf
        tmp="$(mktemp)"
        printf '# Generated by bootstrap/60-alerting.sh — see that script for why.\n[Service]\nExecStart=\nExecStart=%s --savestates=/var/lib/smartd/\n' \
            "$base_exec" > "$tmp"
        if [[ -f "$dropin" ]] && cmp -s -- "$tmp" "$dropin"; then
            dbg "smartd savestates drop-in already current"
        else
            log "adding the smartd savestates drop-in"
            run install -Dm644 -- "$tmp" "$dropin"
            smartd_changed=1
        fi
        rm -f -- "$tmp"
    fi
fi

unit_reload
unit_enable --now smartd.service
if [[ -n "${smartd_changed:-}" && -z "$DRY_RUN" ]]; then
    log "restarting smartd for the new configuration"
    run systemctl restart smartd.service
fi

# ---------------------------------------------------------------------------
# Timers
# ---------------------------------------------------------------------------
unit_enable --now homelab-heartbeat.timer
unit_enable --now smart-snapshot.timer

# ---------------------------------------------------------------------------
# Prove it end to end
# ---------------------------------------------------------------------------
if [[ -z "$DRY_RUN" ]]; then
    systemctl is-active --quiet smartd.service \
        || { journalctl -u smartd -n 20 --no-pager >&2 || true; die "smartd is not running"; }

    log "taking the first SMART snapshot (this is the baseline for every delta)"
    /usr/local/bin/smart-snapshot >&2 || warn "smart-snapshot reported a problem"

    log "sending a test notification — check your phone"
    /usr/local/bin/ntfy-alert \
        "$TARGET_HOSTNAME: alerting configured" \
        "If you are reading this, ntfy works. Unit failures, SMART changes and SnapRAID results will arrive the same way." \
        default "white_check_mark" \
        || die "the test notification failed — fix this now, or none of the alerting above is real"

    systemctl list-timers --no-pager 'homelab-*' 'smart-*' 'snapraid-*' >&2 || true
fi

cat >&2 <<'EOF'

  Two things this cannot verify for you:

    1. That the ntfy message actually arrived. Check your phone.
    2. That the Healthchecks dead-man switches alert on silence. The only
       honest test is to stop the heartbeat timer and wait for the grace
       period to expire:

           sudo systemctl stop homelab-heartbeat.timer
           # wait out the grace period, confirm the alert arrives
           sudo systemctl start homelab-heartbeat.timer

       Worth doing once. An untested dead-man switch is an assumption,
       and this one is carrying "the house server is down".
EOF

ok "alerting configured"
