#!/usr/bin/env bash
# bootstrap/70-podman.sh — the container runtime, and nothing running on it.
#
# Rootful Podman with Quadlet units, no daemon. Applications are systemd
# services: `systemctl status immich`, `journalctl -u frigate`, restart policy
# via Restart=always. That is the management interface, and it is why there is
# no Portainer here — the muscle memory you already have IS the tool.
#
# This script stands up the platform. Applications are the next stage, and each
# arrives as unit files in apps/ symlinked into /etc/containers/systemd/.
#
# Idempotent.

# shellcheck source=lib/common.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"

require_root
require_installed_system
load_host_conf

QUADLET_DIR=/etc/containers/systemd
APPDATA=/opt/appdata

# ---------------------------------------------------------------------------
# Where container state lives
# ---------------------------------------------------------------------------
# Both of these were provisioned by install/: @containers is its own Btrfs
# subvolume mounted at /var/lib/containers, and /opt/appdata is the ext4
# partition. Neither is created here — they are checked, because podman writing
# to the root filesystem instead would be silent until the SSD filled.
findmnt -no TARGET /var/lib/containers >/dev/null 2>&1 \
    || die "/var/lib/containers is not a separate subvolume — image layers would land on @ and be captured by every snapshot"
findmnt -no TARGET "$APPDATA" >/dev/null 2>&1 \
    || die "$APPDATA is not mounted — application state would land on the root filesystem"

# ---------------------------------------------------------------------------
# Podman
# ---------------------------------------------------------------------------
# netavark and aardvark-dns are the current network stack; passt/pasta provides
# unprivileged networking. Named explicitly rather than relying on them being
# pulled in, for the same reason inotify-tools was in bootstrap/20.
pkg_install podman netavark aardvark-dns passt

run mkdir -p -- "$QUADLET_DIR"

# The Docker-compatible API, socket-activated so nothing runs until something
# connects. Homepage's container-status tiles speak this protocol.
#
# Worth knowing before any application uses it: access to this socket is
# equivalent to root on the host. When Homepage arrives it gets a read-only
# proxy in front of it, never the socket itself.
unit_enable podman.socket
run systemctl start podman.socket

# ---------------------------------------------------------------------------
# Automatic updates
# ---------------------------------------------------------------------------
# podman-auto-update pulls newer images for containers labelled
# io.containers.autoupdate=registry, restarts their services, and — the part no
# Docker-side tool does cleanly — rolls back to the previous image if the
# updated service fails to come up. Update policy is expressed by which tag
# each unit tracks, not by a schedule.
install_file usr/local/bin/podman-auto-update-run 0755
install_file etc/systemd/system/podman-auto-update.timer.d/10-schedule.conf

# Override ExecStart to go through the wrapper, built from whatever the package
# ships rather than a hardcoded command line.
if [[ -z "$DRY_RUN" ]]; then
    dropin=/etc/systemd/system/podman-auto-update.service.d/10-homelab.conf
    tmp="$(mktemp)"
    printf '# Generated by bootstrap/70-podman.sh.\n[Unit]\nOnFailure=ntfy-alert@%%n.service\n\n[Service]\nExecStart=\nExecStart=/usr/local/bin/podman-auto-update-run\n' > "$tmp"
    if [[ -f "$dropin" ]] && cmp -s -- "$tmp" "$dropin"; then
        dbg "auto-update drop-in already current"
    else
        log "installing the auto-update drop-in"
        run install -Dm644 -- "$tmp" "$dropin"
    fi
    rm -f -- "$tmp"
fi

install_file etc/systemd/system/podman-image-prune.service
install_file etc/systemd/system/podman-image-prune.timer

unit_reload
unit_enable --now podman-auto-update.timer
unit_enable --now podman-image-prune.timer

# ---------------------------------------------------------------------------
# Verify
# ---------------------------------------------------------------------------
if [[ -z "$DRY_RUN" ]]; then
    podman info >/dev/null 2>&1 || die "podman info failed — the runtime is not usable"

    # A real container, pulled and run and removed. `podman info` succeeding
    # proves configuration parses; it does not prove the machine can pull an
    # image and execute one, which is the thing every later stage depends on.
    log "running a throwaway container to prove the runtime works end to end"
    if podman run --rm docker.io/library/alpine:latest true 2>&1; then
        ok "pulled and ran a container"
        run podman rmi -f docker.io/library/alpine:latest
    else
        die "could not pull and run a test container — fix this before any application depends on it"
    fi

    systemctl list-timers --no-pager 'podman-*' >&2 || true
fi

cat >&2 <<EOF

  The platform is up. Applications come next, and each one is:

    apps/<name>/<name>.container      a Quadlet unit, in git
    $APPDATA/<name>/                  its state, on ext4
    /mnt/pool/<...>                    its bulk data, on the pool

  Two things every app unit needs, and neither is optional:

    RequiresMountsFor=$APPDATA /mnt/pool
        so a failed mount stops the service instead of being written around

    io.containers.autoupdate=registry
        or it never updates — and the tag it tracks IS the update policy

  Deliberately not configured here: a read-only proxy in front of
  podman.socket. Nothing consumes the socket yet, and it arrives with
  Homepage. Access to that socket is root on this host, so no container
  gets it directly.
EOF

ok "Podman platform ready"
