#!/usr/bin/env bash
# bootstrap/80-backup.sh — off-site backups with restic to Backblaze B2.
#
# This is the first thing on this machine that protects against something other
# than a drive dying. SnapRAID handles a failed disk; it does not handle a
# deleted directory, a bad migration, ransomware, a house fire, or the day you
# type the wrong path as root. Those all need a copy somewhere else.
#
# What is backed up and HOW each thing must be captured is specified in
# docs/backup-inventory.md. This script implements it; that file is the reason.
#
# Idempotent. Does NOT initialise the repository — see the note at the end.

# shellcheck source=lib/common.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/common.sh"

require_root
require_installed_system
load_host_conf

# Mandatory here rather than at load time: this is the script that uses them.
require_conf RESTIC_REPOSITORY RESTIC_PASSWORD

ENV_DIR=/etc/homelab
ENV_FILE="$ENV_DIR/backup.env"

# sqlite3 for the SQLite dumps; restic needs no help for B2 (it speaks the API
# natively, so there is no rclone in this picture).
pkg_install restic sqlite

# ---------------------------------------------------------------------------
# Credentials
# ---------------------------------------------------------------------------
# RESTIC_PASSWORD is the encryption key for the entire repository. Lose it and
# every backup you have is unreadable noise — there is no recovery, by design.
# It is generated by you, stored in host.conf, and host.conf belongs in your
# password manager AND somewhere reachable when the password manager is the
# thing that is down.
run mkdir -p -- "$ENV_DIR"
run chmod 0700 -- "$ENV_DIR"

env_tmp="$(mktemp)"
chmod 0600 -- "$env_tmp"
{
    printf '# Generated by bootstrap/80-backup.sh from host.conf. Not in git.\n'
    printf 'RESTIC_REPOSITORY=%q\n' "$RESTIC_REPOSITORY"
    printf 'RESTIC_PASSWORD=%q\n'   "$RESTIC_PASSWORD"
    printf 'B2_ACCOUNT_ID=%q\n'     "${B2_ACCOUNT_ID:-}"
    printf 'B2_ACCOUNT_KEY=%q\n'    "${B2_ACCOUNT_KEY:-}"
    printf 'RESTIC_LIMIT_UPLOAD=%q\n' "${RESTIC_LIMIT_UPLOAD:-}"
    printf 'RESTIC_KEEP_DAILY=%q\n'   "${RESTIC_KEEP_DAILY:-7}"
    printf 'RESTIC_KEEP_WEEKLY=%q\n'  "${RESTIC_KEEP_WEEKLY:-5}"
    printf 'RESTIC_KEEP_MONTHLY=%q\n' "${RESTIC_KEEP_MONTHLY:-12}"
    # Immich's database credentials are NOT copied here. They live in
    # apps/immich/immich.env, which is where they are defined; homelab-backup
    # reads them from there. The same fact in two files is a fact that drifts.
} > "$env_tmp"

if [[ -f "$ENV_FILE" ]] && cmp -s -- "$env_tmp" "$ENV_FILE"; then
    rm -f -- "$env_tmp"
else
    log "writing $ENV_FILE"
    run install -Dm600 -- "$env_tmp" "$ENV_FILE"
    rm -f -- "$env_tmp"
fi

# ---------------------------------------------------------------------------
# The job
# ---------------------------------------------------------------------------
install_file usr/local/bin/homelab-backup 0755
install_file etc/systemd/system/homelab-backup.service
install_file etc/systemd/system/homelab-backup.timer
install_file etc/systemd/system/homelab-backup-check.service
install_file etc/systemd/system/homelab-backup-check.timer

# Staging lives here, briefly, during each run. 0700 because for the length of
# a backup it contains every database and every secret on this host in one
# directory.
run mkdir -p -- /var/lib/homelab/backup
run chmod 0700 -- /var/lib/homelab
run chmod 0700 -- /var/lib/homelab/backup

unit_reload
unit_enable --now homelab-backup.timer
unit_enable --now homelab-backup-check.timer

# ---------------------------------------------------------------------------
# Is there a repository yet?
# ---------------------------------------------------------------------------
# `restic init` is NOT run here, and that is deliberate. Initialising a
# repository is a one-time act against a remote bucket; doing it automatically
# from a provisioning script means a typo in RESTIC_REPOSITORY silently creates
# a second, empty repository rather than failing to find the real one — and the
# first you would know is a restore that comes back empty.
# shellcheck source=/dev/null
set -a; source "$ENV_FILE"; set +a
if restic snapshots >/dev/null 2>&1; then
    count="$(restic snapshots --json 2>/dev/null | grep -o '"time"' | wc -l || echo 0)"
    ok "repository reachable — $count snapshot(s)"
else
    warn "no repository at $RESTIC_REPOSITORY yet (or credentials are wrong)."
    warn "Create it once, by hand, after checking the value is exactly right:"
    warn ""
    warn "  set -a; . /etc/homelab/backup.env; set +a"
    warn "  restic init"
    warn ""
    warn "Then run the first backup in the foreground and watch it:"
    warn "  sudo systemctl start homelab-backup.service"
    warn "  journalctl -u homelab-backup -f"
fi

cat >&2 <<EOF

  ────────────────────────────────────────────────────────────
  RESTIC_PASSWORD is the encryption key for every backup you
  have. There is no recovery without it, by design.

  It lives in host.conf. Put host.conf in Vaultwarden — and
  ALSO somewhere you can reach when Vaultwarden is the thing
  that is down. Printed in a drawer counts.

  A backup you have never restored is a hypothesis. The drill
  is in docs/backup-inventory.md and belongs in Phase 5.
  ────────────────────────────────────────────────────────────
EOF

ok "backups configured — next: run one and watch it"
